### ISSUE TITLE
Check for updates fails if UI2 is using SSL

### ISSUE THREAD

**Issue by astradtner** [bp2008/ui2#1]
Check for updates fails if UI2 is running using SSL. Chrome console shows a mixed content warning:

Mixed Content: The page at '<location>/ui2.htm' was loaded over HTTPS, but requested an insecure script 'http://www.ipcamtalk.com/bp08/ui2_version.js?nocache=1492458412418&_=1492458395866'. This request has been blocked; the content must be served over HTTPS.

Is it possible to move that js file to a server with SSL?

**Comment by bp2008** [comment]
Indeed, ipcamtalk does support SSL these days (maybe always has).  I will update the URL in UI2 so this fix will be in the next release...  whenever that happens to be.

**Comment by bp2008** [comment]
This fix has been released!
